In [58]:
import pandas as pd
import numpy as np
from pandas import get_dummies
from sklearn.preprocessing import MinMaxScaler

In [59]:
df = pd.read_csv("train.csv")

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7205 entries, 0 to 7204
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   VehicleID               7205 non-null   object 
 1   Location                7205 non-null   object 
 2   Maker                   7205 non-null   object 
 3   Model                   7205 non-null   object 
 4   Year                    7184 non-null   object 
 5   Colour                  7205 non-null   object 
 6   Amount (Million Naira)  7188 non-null   float64
 7   Type                    7008 non-null   object 
 8   Distance                4845 non-null   object 
dtypes: float64(1), object(8)
memory usage: 506.7+ KB


In [61]:
df.Year = df.Year.fillna(value = "2008")

In [62]:
df.Year.isnull().sum()

0

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7205 entries, 0 to 7204
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   VehicleID               7205 non-null   object 
 1   Location                7205 non-null   object 
 2   Maker                   7205 non-null   object 
 3   Model                   7205 non-null   object 
 4   Year                    7205 non-null   object 
 5   Colour                  7205 non-null   object 
 6   Amount (Million Naira)  7188 non-null   float64
 7   Type                    7008 non-null   object 
 8   Distance                4845 non-null   object 
dtypes: float64(1), object(8)
memory usage: 506.7+ KB


In [64]:
df.Type.value_counts()

Foreign Used     4896
Nigerian Used    1895
Brand New         217
Name: Type, dtype: int64

In [65]:
df.Type = df.Type.fillna(value = 'Foreign Used')

In [66]:
df.Type.isnull().sum()

0

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7205 entries, 0 to 7204
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   VehicleID               7205 non-null   object 
 1   Location                7205 non-null   object 
 2   Maker                   7205 non-null   object 
 3   Model                   7205 non-null   object 
 4   Year                    7205 non-null   object 
 5   Colour                  7205 non-null   object 
 6   Amount (Million Naira)  7188 non-null   float64
 7   Type                    7205 non-null   object 
 8   Distance                4845 non-null   object 
dtypes: float64(1), object(8)
memory usage: 506.7+ KB


In [68]:
df.Distance.value_counts()

75,000     70
65,000     54
85,000     53
100,000    53
50,000     47
           ..
10,559      1
56,443      1
86,582      1
175,294     1
83,308      1
Name: Distance, Length: 3144, dtype: int64

In [69]:
df.Distance = df.Distance.fillna(value ='75,000')

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7205 entries, 0 to 7204
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   VehicleID               7205 non-null   object 
 1   Location                7205 non-null   object 
 2   Maker                   7205 non-null   object 
 3   Model                   7205 non-null   object 
 4   Year                    7205 non-null   object 
 5   Colour                  7205 non-null   object 
 6   Amount (Million Naira)  7188 non-null   float64
 7   Type                    7205 non-null   object 
 8   Distance                7205 non-null   object 
dtypes: float64(1), object(8)
memory usage: 506.7+ KB


In [71]:
df.drop("VehicleID", axis = 1, inplace  = True)

In [72]:
df.drop("Model", axis = 1, inplace  = True)

In [73]:
import seaborn as sns

In [74]:
df["Amount (Million Naira)"].isnull().sum()

17

In [75]:
mean = np.mean(df["Amount (Million Naira)"])

In [76]:
mean

11.847999443516994

In [77]:
df["Amount (Million Naira)"] = df["Amount (Million Naira)"].fillna(value = 11.847999443516994)

In [78]:
df["Amount (Million Naira)"].isnull().sum()

0

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7205 entries, 0 to 7204
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Location                7205 non-null   object 
 1   Maker                   7205 non-null   object 
 2   Year                    7205 non-null   object 
 3   Colour                  7205 non-null   object 
 4   Amount (Million Naira)  7205 non-null   float64
 5   Type                    7205 non-null   object 
 6   Distance                7205 non-null   object 
dtypes: float64(1), object(6)
memory usage: 394.1+ KB


In [80]:
for col in df.columns:
    print(col, df[col].unique(), sep = ":", end = '\n\n' )
    

Location:['Abuja' 'Ibadan' 'Lagos']

Maker:['Honda' 'Hyundai' 'Lexus' 'Mercedes-Benz' 'Toyota' 'Acura' 'Dodge'
 'Nissan' 'Kia' 'BMW' 'Volvo' 'Ford' 'Land Rover' 'Lincoln' 'Peugeot'
 'Chevrolet' 'Audi' 'Jaguar' 'Infiniti' 'Porsche' 'Fiat' 'Maserati'
 'Volkswagen' 'Suzuki' 'Bentley' 'GAC' 'Mazda' 'Scion' 'Renault'
 'Mitsubishi' 'Mini' 'Pontiac' 'Cadillac' 'Ferrari' 'Jeep' 'Buick'
 'Rolls-Royce' 'GMC' 'Chrysler' 'Lamborghini' 'Citroen' 'King' 'BAW'
 'Saturn' 'Tata' 'Opel' 'JAC' 'MG' 'Hummer' 'Subaru' 'Rover' 'Saab'
 'Skoda' 'IVM' 'Brabus']

Year:['2,011' '2,012' '2,010' '2,017' '2,002' '2,019' '2,015' '2,004' '2,003'
 '2,008' '2,018' '2,020' '2,006' '2,016' '2,014' '2,007' '2,009' '2,005'
 '2,021' '2,013' '2,000' '2008' '1,992' '2,001' '1,997' '1,999' '1,993'
 '1,998' '1,986' '1,996' '2,022' '1,995' '1,979' '1,989']

Colour:['Silver' 'Red' 'Blue' 'Black' 'Gold' 'White' 'Gray' 'Burgandy' 'Green'
 'Violet' 'Brown' 'Yellow' 'Orange' 'Pink' 'Beige' 'Purple' 'Ivory' 'G'
 'Teal' 'Mica' 'Pearl']

In [81]:
df.Year.describe()


count      7205
unique       34
top       2,008
freq        755
Name: Year, dtype: object

In [82]:
from sklearn.preprocessing import LabelEncoder
#instantiate --- assign the labelencoder algorithm in to a container
lab_enc = LabelEncoder()
df["Year"] = lab_enc.fit_transform(df["Year"])
df.Distance= lab_enc.fit_transform(df["Distance"])
df["Colour"] = lab_enc.fit_transform(df["Colour"])
df.Maker= lab_enc.fit_transform(df["Maker"])

In [83]:
df

Location  Maker  Year  Colour  Amount (Million Naira)           Type  \
0       Abuja     17    21      16                    2.20  Nigerian Used   
1      Ibadan     19    22      16                    3.50  Nigerian Used   
2       Lagos     29    20      15                    9.20   Foreign Used   
3       Abuja     34    27       2                   22.80   Foreign Used   
4      Ibadan     52    12      15                    2.60  Nigerian Used   
...       ...    ...   ...     ...                     ...            ...   
7200    Abuja     17    28       7                    5.70   Foreign Used   
7201    Abuja      3    17      19                    4.00  Nigerian Used   
7202    Abuja     52    20       1                    2.85  Nigerian Used   
7203    Lagos     34    22       1                    8.65   Foreign Used   
7204    Abuja     17    22       7                    3.38  Nigerian Used   

      Distance  
0         2496  
1          466  
2          235  
3         1446  
4          470  
...        ...  
7200      2240  
7201      1107  
7202      2496  
7203      2783  
7204      2699  

[7205 rows x 7 columns]

In [84]:
# col_to_encode = ['Type',  'Location', 'Year', 'Maker', 'Colour']
col_to_encode = ['Type',  'Location']
encoded = get_dummies(df, columns=col_to_encode, prefix='coded', drop_first = True)


In [85]:
encoded

Maker  Year  Colour  Amount (Million Naira)  Distance  \
0        17    21      16                    2.20      2496   
1        19    22      16                    3.50       466   
2        29    20      15                    9.20       235   
3        34    27       2                   22.80      1446   
4        52    12      15                    2.60       470   
...     ...   ...     ...                     ...       ...   
7200     17    28       7                    5.70      2240   
7201      3    17      19                    4.00      1107   
7202     52    20       1                    2.85      2496   
7203     34    22       1                    8.65      2783   
7204     17    22       7                    3.38      2699   

      coded_Foreign Used  coded_Nigerian Used  coded_Ibadan  coded_Lagos  
0                      0                    1             0            0  
1                      0                    1             1            0  
2                      1                    0             0            1  
3                      1                    0             0            0  
4                      0                    1             1            0  
...                  ...                  ...           ...          ...  
7200                   1                    0             0            0  
7201                   0                    1             0            0  
7202                   0                    1             0            0  
7203                   1                    0             0            1  
7204                   0                    1             0            0  

[7205 rows x 9 columns]

In [86]:
X =  encoded.drop("Amount (Million Naira)", axis = 1)
y =  encoded["Amount (Million Naira)"]  #data.tip

In [87]:
X

Maker  Year  Colour  Distance  coded_Foreign Used  coded_Nigerian Used  \
0        17    21      16      2496                   0                    1   
1        19    22      16       466                   0                    1   
2        29    20      15       235                   1                    0   
3        34    27       2      1446                   1                    0   
4        52    12      15       470                   0                    1   
...     ...   ...     ...       ...                 ...                  ...   
7200     17    28       7      2240                   1                    0   
7201      3    17      19      1107                   0                    1   
7202     52    20       1      2496                   0                    1   
7203     34    22       1      2783                   1                    0   
7204     17    22       7      2699                   0                    1   

      coded_Ibadan  coded_Lagos  
0                0            0  
1                1            0  
2                0            1  
3                0            0  
4                1            0  
...            ...          ...  
7200             0            0  
7201             0            0  
7202             0            0  
7203             0            1  
7204             0            0  

[7205 rows x 8 columns]

In [88]:
y

0        2.20
1        3.50
2        9.20
3       22.80
4        2.60
        ...  
7200     5.70
7201     4.00
7202     2.85
7203     8.65
7204     3.38
Name: Amount (Million Naira), Length: 7205, dtype: float64

In [89]:
scaler = MinMaxScaler()

In [90]:
scaled_x = scaler.fit_transform(X) 
scaled_x

array([[0.31481481, 0.63636364, 0.8       , ..., 1.        , 0.        ,
        0.        ],
       [0.35185185, 0.66666667, 0.8       , ..., 1.        , 1.        ,
        0.        ],
       [0.53703704, 0.60606061, 0.75      , ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.96296296, 0.60606061, 0.05      , ..., 1.        , 0.        ,
        0.        ],
       [0.62962963, 0.66666667, 0.05      , ..., 0.        , 0.        ,
        1.        ],
       [0.31481481, 0.66666667, 0.35      , ..., 1.        , 0.        ,
        0.        ]])

In [91]:
scaled_x = pd.DataFrame(data = scaled_x, index = X.index, columns = X.columns)

In [92]:
scaled_x.head()

Maker      Year  Colour  Distance  coded_Foreign Used  \
0  0.314815  0.636364    0.80  0.794146                 0.0   
1  0.351852  0.666667    0.80  0.148266                 0.0   
2  0.537037  0.606061    0.75  0.074769                 1.0   
3  0.629630  0.818182    0.10  0.460070                 1.0   
4  0.962963  0.363636    0.75  0.149539                 0.0   

   coded_Nigerian Used  coded_Ibadan  coded_Lagos  
0                  1.0           0.0          0.0  
1                  1.0           1.0          0.0  
2                  0.0           0.0          1.0  
3                  0.0           0.0          0.0  
4                  1.0           1.0          0.0

In [93]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(scaled_x, y, test_size=0.2, random_state=30)

In [94]:
X_train.head(3)

Maker      Year  Colour  Distance  coded_Foreign Used  \
1315  0.537037  0.787879    0.95  0.715240                 1.0   
5101  0.537037  0.454545    0.80  0.965956                 0.0   
3932  0.537037  0.545455    0.10  0.316895                 0.0   

      coded_Nigerian Used  coded_Ibadan  coded_Lagos  
1315                  0.0           0.0          1.0  
5101                  1.0           0.0          0.0  
3932                  1.0           1.0          0.0

In [95]:
from sklearn.linear_model import LinearRegression

In [96]:
dt = LinearRegression()

In [97]:
dt.fit(X_train, y_train)

LinearRegression()

In [98]:
dt_pred = dt.predict(X_test)

In [99]:
dt_pred[:3]

array([ 8.72867132, 16.93336757, 18.8516138 ])

In [100]:
from sklearn.tree import DecisionTreeRegressor   # algorithm alternative to linear regression
from sklearn.metrics import r2_score, mean_absolute_error # for evaluation
from sklearn.metrics import mean_squared_error

In [101]:
print('R2: ', r2_score(y_test, dt_pred))
print('mae: ', mean_absolute_error(y_test, dt_pred))

print('mse: ', mean_squared_error(y_test, dt_pred))

R2:  0.2626294173930117
mae:  6.947245439353033
mse:  323.93629526390464


In [102]:
dr = DecisionTreeRegressor()
dr.fit(X_train, y_train)
dr_pred = dr.predict(X_test)
dr_pred[:3]

array([ 5.5, 12.5, 16.8])

In [103]:
print('R2: ', r2_score(y_test, dr_pred))
print('mae: ', mean_absolute_error(y_test, dr_pred))

print('mse: ', mean_squared_error(y_test, dr_pred))

R2:  0.3503069917714118
mae:  5.290767383387052
mse:  285.4184193249857


In [104]:
from xgboost import XGBRegressor
xgb = XGBRegressor()
xgb.fit(X_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
             importance_type=None, interaction_constraints='',
             learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
             max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
             missing=nan, monotone_constraints='()', n_estimators=100, n_jobs=0,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, ...)

In [105]:
xgb_pred = xgb.predict(X_test)
xgb_pred[:3]

array([ 7.456703, 13.908311, 21.30121 ], dtype=float32)

In [106]:
print('R2: ', r2_score(y_test, xgb_pred))
print('mae: ', mean_absolute_error(y_test, xgb_pred))

print('mse: ', mean_squared_error(y_test, xgb_pred))


R2:  0.6759791965742428
mae:  4.293771763494289
mse:  142.34646882586247


In [107]:
from math import sqrt  #function for square

sqrt(mean_squared_error(y_test, xgb_pred))





11.930903940014876

In [108]:
sqrt(mean_squared_error(y_test, dt_pred))

17.998230337005488

In [109]:
sqrt(mean_squared_error(y_test, dr_pred))

16.89433098187039

In [110]:
dr = pd.read_csv("Test.csv")

In [111]:
dr


VehicleID Location    Maker                  Model   Year  Colour  \
0     VHL18518    Abuja      BMW                   323i  2,008   White   
1     VHL17149    Lagos   Toyota                  Camry  2,013   White   
2     VHL10927    Lagos   Toyota  Highlander Limited V6  2,005    Gold   
3     VHL12909    Lagos   Toyota                  Camry  2,011    Gray   
4     VHL12348    Lagos    Lexus             ES 350 FWD  2,013     Red   
...        ...      ...      ...                    ...    ...     ...   
2056  VHL17903    Abuja   Toyota                 Avalon  2,020     Red   
2057  VHL14018   Ibadan     Audi                     Q5  2,011    Blue   
2058  VHL17473   Ibadan   Toyota                  Camry  2,015   Black   
2059  VHL11480    Abuja    Lexus             IS 350 AWD  2,013   White   
2060  VHL13881    Abuja  Pontiac                Torrent  2,009  Silver   

              Type  Distance  
0     Foreign Used   30524.0  
1     Foreign Used       NaN  
2     Foreign Used       NaN  
3     Foreign Used  166839.0  
4     Foreign Used   88862.0  
...            ...       ...  
2056  Foreign Used    2650.0  
2057  Foreign Used   99000.0  
2058  Foreign Used  108000.0  
2059  Foreign Used   52485.0  
2060  Foreign Used  124088.0  

[2061 rows x 8 columns]

In [112]:
dr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2061 entries, 0 to 2060
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   VehicleID  2061 non-null   object 
 1   Location   2061 non-null   object 
 2   Maker      2061 non-null   object 
 3   Model      2061 non-null   object 
 4   Year       2059 non-null   object 
 5   Colour     2061 non-null   object 
 6   Type       2007 non-null   object 
 7   Distance   1385 non-null   float64
dtypes: float64(1), object(7)
memory usage: 128.9+ KB


In [113]:
dr.shape

(2061, 8)

In [114]:
dr.drop("Model", axis = 1, inplace = True)

In [115]:
dr.Year = dr.Year.fillna(value = '2008')

In [116]:
dr.Year.isnull().sum()

0

In [117]:
dr.Type.value_counts()

Foreign Used     1390
Nigerian Used     547
Brand New          70
Name: Type, dtype: int64

In [118]:
dr.Type = dr.Type.fillna(value = 'Foreign Used')

In [119]:
dr.Type.isnull().sum()

0

In [120]:
meann = np.mean(dr.Distance)

In [121]:
meann

103800.66859205776

In [122]:
dr.Distance= dr.Distance.fillna(value = 103800.66859205776)

In [123]:
dr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2061 entries, 0 to 2060
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   VehicleID  2061 non-null   object 
 1   Location   2061 non-null   object 
 2   Maker      2061 non-null   object 
 3   Year       2061 non-null   object 
 4   Colour     2061 non-null   object 
 5   Type       2061 non-null   object 
 6   Distance   2061 non-null   float64
dtypes: float64(1), object(6)
memory usage: 112.8+ KB


In [124]:
for col in dr.columns:
    print(col, dr[col].unique(), sep = ":", end = '\n\n' )

VehicleID:['VHL18518' 'VHL17149' 'VHL10927' ... 'VHL17473' 'VHL11480' 'VHL13881']

Location:['Abuja' 'Lagos' 'Ibadan']

Maker:['BMW' 'Toyota' 'Lexus' 'Mercedes-Benz' 'Honda' 'Pontiac' 'Hyundai'
 'Land Rover' 'Mitsubishi' 'Volkswagen' 'Acura' 'Mazda' 'Ford' 'Jaguar'
 'Opel' 'Infiniti' 'Kia' 'Peugeot' 'Nissan' 'Chevrolet' 'Cadillac' 'Seat'
 'Audi' 'Porsche' 'Dodge' 'GMC' 'Renault' 'Lincoln' 'Maserati' 'Chrysler'
 'Fiat' 'Subaru' 'Mini' 'Scion' 'Buick' 'Rolls-Royce' 'Volvo' 'Jeep'
 'Lamborghini' 'Brabus']

Year:['2,008' '2,013' '2,005' '2,011' '2,017' '1,999' '2,019' '2,006' '2,015'
 '2,007' '2,012' '2,016' '2,010' '2,003' '2,004' '2,021' '2008' '2,018'
 '2,014' '2,009' '2,001' '2,022' '2,002' '2,020' '1,997' '2,000' '1,998'
 '1,986' '1,991' '1,982']

Colour:['White' 'Gold' 'Gray' 'Red' 'Black' 'Blue' 'Silver' 'Brown' 'Green'
 'Purple' 'Beige' 'Burgandy' 'Auto' 'Cream' 'Pink' 'Yellow' 'V' 'Teal']

Type:['Foreign Used' 'Nigerian Used' 'Brand New']

Distance:[ 30524.         103800.66859206

In [125]:
dr["Year"] = lab_enc.fit_transform(dr["Year"])
dr["Colour"] = lab_enc.fit_transform(dr["Colour"])
dr["Maker"] = lab_enc.fit_transform(dr["Maker"])
dr["Maker"] = lab_enc.fit_transform(dr["Distance"])

In [126]:
col_to_encod = ['Type',  'Location']
encod = get_dummies(dr, columns=col_to_encod, prefix='coded', drop_first = True)
encod

VehicleID  Maker  Year  Colour       Distance  coded_Foreign Used  \
0     VHL18518    131    14      16   30524.000000                   1   
1     VHL17149    626    19      16  103800.668592                   1   
2     VHL10927    626    11       7  103800.668592                   1   
3     VHL12909    839    17       8  166839.000000                   1   
4     VHL12348    528    19      12   88862.000000                   1   
...        ...    ...   ...     ...            ...                 ...   
2056  VHL17903     32    26      12    2650.000000                   1   
2057  VHL14018    604    17       3   99000.000000                   1   
2058  VHL17473    643    21       2  108000.000000                   1   
2059  VHL11480    244    19      16   52485.000000                   1   
2060  VHL13881    722    15      13  124088.000000                   1   

      coded_Nigerian Used  coded_Ibadan  coded_Lagos  
0                       0             0            0  
1                       0             0            1  
2                       0             0            1  
3                       0             0            1  
4                       0             0            1  
...                   ...           ...          ...  
2056                    0             0            0  
2057                    0             1            0  
2058                    0             1            0  
2059                    0             0            0  
2060                    0             0            0  

[2061 rows x 9 columns]

In [127]:
X =  encod.drop("VehicleID", axis = 1)
# y =  encoded["Amount (Million Naira)"]  #data.tip

In [128]:
scaled_xx = scaler.fit_transform(X) 
scaled_xx

array([[0.12843137, 0.48275862, 0.94117647, ..., 0.        , 0.        ,
        0.        ],
       [0.61372549, 0.65517241, 0.94117647, ..., 0.        , 0.        ,
        1.        ],
       [0.61372549, 0.37931034, 0.41176471, ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.63039216, 0.72413793, 0.11764706, ..., 0.        , 1.        ,
        0.        ],
       [0.23921569, 0.65517241, 0.94117647, ..., 0.        , 0.        ,
        0.        ],
       [0.70784314, 0.51724138, 0.76470588, ..., 0.        , 0.        ,
        0.        ]])

In [129]:
scaled_xx = pd.DataFrame(data = scaled_xx, index = X.index, columns = X.columns)
scaled_xx.head()

Maker      Year    Colour  Distance  coded_Foreign Used  \
0  0.128431  0.482759  0.941176  0.030981                 1.0   
1  0.613725  0.655172  0.941176  0.105357                 1.0   
2  0.613725  0.379310  0.411765  0.105357                 1.0   
3  0.822549  0.586207  0.470588  0.169342                 1.0   
4  0.517647  0.655172  0.705882  0.090195                 1.0   

   coded_Nigerian Used  coded_Ibadan  coded_Lagos  
0                  0.0           0.0          0.0  
1                  0.0           0.0          1.0  
2                  0.0           0.0          1.0  
3                  0.0           0.0          1.0  
4                  0.0           0.0          1.0

In [130]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5764 entries, 1315 to 5925
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Maker                5764 non-null   float64
 1   Year                 5764 non-null   float64
 2   Colour               5764 non-null   float64
 3   Distance             5764 non-null   float64
 4   coded_Foreign Used   5764 non-null   float64
 5   coded_Nigerian Used  5764 non-null   float64
 6   coded_Ibadan         5764 non-null   float64
 7   coded_Lagos          5764 non-null   float64
dtypes: float64(8)
memory usage: 405.3 KB


In [131]:
scaled_xx.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2061 entries, 0 to 2060
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Maker                2061 non-null   float64
 1   Year                 2061 non-null   float64
 2   Colour               2061 non-null   float64
 3   Distance             2061 non-null   float64
 4   coded_Foreign Used   2061 non-null   float64
 5   coded_Nigerian Used  2061 non-null   float64
 6   coded_Ibadan         2061 non-null   float64
 7   coded_Lagos          2061 non-null   float64
dtypes: float64(8)
memory usage: 128.9 KB


In [132]:
from xgboost import XGBRegressor
xgb = XGBRegressor()
xgb.fit(X_train, y_train)
xgb_predd = xgb.predict(scaled_xx)
xgb_predd[:3]

array([-0.34144503,  6.829136  ,  2.996089  ], dtype=float32)

In [133]:

xgb_predd = pd.DataFrame(data = xgb_predd, columns = ['Amount (Million Naira)'])

In [134]:

xgb_predd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2061 entries, 0 to 2060
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Amount (Million Naira)  2061 non-null   float32
dtypes: float32(1)
memory usage: 8.2 KB


In [135]:
# pd.merge(dr, xgb_predd[["VehicleID", "Amount (Million Naira)"]], on="VehicleID", how="left")
# df_cd = pd.merge(dr, xgb_predd, how='inner', on = 'VehicleID')
rr = pd.merge(dr.VehicleID,xgb_predd, how = 'inner', on = dr["VehicleID"])
rr.drop('key_0', axis = 1, inplace = True)

In [136]:
rr

VehicleID  Amount (Million Naira)
0     VHL18518               -0.341445
1     VHL17149                6.829136
2     VHL17149               12.791060
3     VHL17149                6.829136
4     VHL17149               12.791060
...        ...                     ...
2458  VHL17903                6.272153
2459  VHL14018               11.895899
2460  VHL17473                7.130605
2461  VHL11480               23.229563
2462  VHL13881                2.773290

[2463 rows x 2 columns]

In [137]:
rr.to_csv('finalre1sult.csv',index= False) #-- to remove the index